### ISSUE TITLE
Linkedin link

### ISSUE THREAD

**Issue by stifskere** [DevCaress/links#1]
El link de linkedin no funciona por que falta especificar el protocolo, segun [rfc8288](https://datatracker.ietf.org/doc/html/rfc8288) se ha de especificar el protocolo para redirigir a otro sitio, si no se interpretra como el mismo sitio

Encontrado en https://github.com/DevCaress/links/blob/435b0fdc98b8df7605fcf8251d069c296186a3eb/pages/index.vue#L33

**Comment by DevCaress** [comment]
Uff tienes razón! Lo copie sin el protocolo jajaja 
Gracias!
